services:
  cupcake:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cupcake
    volumes:
      - .:/var/www
    ports:
      - ${APP_PORT:-80}:80
      - 5173:5173
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=cupcake-db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - cupcake-db
    networks:
      - cupcake-network

  cupcake-db:
    image: mysql:8-debian
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: cupcake-db
    ports:
      - "${DB_EXTERNAL_PORT:-3306}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=mysqlroot
    volumes:
      - cupcake-db-mysql:/var/lib/mysql
    networks:
      - cupcake-network

networks:
  cupcake-network:
    driver: bridge

volumes:
  cupcake-db-mysql:
    driver: local
